version: 2

models:
  - name: stg_orders
    description: "Staged orders with cleaned data types"
    columns:
      - name: order_id
        description: "Primary key for orders"
        tests:
          - not_null
          - unique
      - name: customer_id
        description: "Foreign key to customer"
        tests:
          - not_null
      - name: status
        description: "Order status (pending, completed, cancelled)"
        tests:
          - accepted_values:
              values: ['pending', 'completed', 'cancelled']

  - name: dim_customers
    description: "Customer dimension with aggregated order metrics"
    columns:
      - name: customer_id
        description: "Primary key for customers"
        tests:
          - not_null
          - unique

unit_tests:
  - name: test_customer_status_aggregation
    description: "Verify completed and pending order counts are calculated correctly"
    model: dim_customers
    given:
      - input: ref('stg_orders')
        rows:
          - {order_id: 1, customer_id: 100, status: "completed", amount: 50.00, order_date: "2024-01-01", loaded_at: "2024-01-01 00:00:00"}
          - {order_id: 2, customer_id: 100, status: "pending", amount: 30.00, order_date: "2024-01-02", loaded_at: "2024-01-02 00:00:00"}
          - {order_id: 3, customer_id: 100, status: "completed", amount: 20.00, order_date: "2024-01-03", loaded_at: "2024-01-03 00:00:00"}
    expect:
      rows:
        - {customer_id: 100, total_orders: 3, completed_orders: 2, pending_orders: 1, total_amount: 100.00}
